name: Update Stats in index

on:
  push:
    paths:
      - 'stats.json'

concurrency:
  group: stats-update-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Update index with Stats
        run: |
          node .github/scripts/update-stats.js
          
      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git fetch origin main
          
          git add index.html
          git commit -m "Update stats in index" || echo "No changes to commit"
          
          max_attempts=3
          attempt=1
          until git push origin HEAD:main || [ $attempt -ge $max_attempts ]
          do
            echo "Push failed, retrying in 5 seconds... (Attempt $attempt of $max_attempts)"
            sleep 5
            git pull --rebase origin main
            ((attempt++))
          done
          
          if [ $attempt -ge $max_attempts ]; then
            echo "Failed to push after $max_attempts attempts"
            exit 1
          fi
