name: Update Stats in index

on:
  push:
    paths:
      - 'stats.json'

jobs:
  update-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Update index with Stats
        run: |
          node .github/scripts/update-stats.js
          
      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          
          git pull --rebase origin main
          
          git add index.html
          git commit -m "Update stats in HTML" || echo "No changes to commit"
          git push origin HEAD:main
